#!/usr/bin/env bash
#
# generate-gitignore.sh — Auto-detect project language and generate .gitignore.

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=_lib/common.sh
source "${SCRIPT_DIR}/_lib/common.sh"

TEMPLATES_GITIGNORE="${TEMPLATES_DIR}/gitignore"

print_usage() {
  cat <<EOF
Usage: generate-gitignore.sh [--force] [--lang LANG]

Detects project type(s) and generates .gitignore.
Multiple languages can be merged.

Options:
  --force        Overwrite existing .gitignore (default: append)
  --lang LANG    Force specific language (node/python/java/go/rust/dotnet)
  --dry-run      Show what would be generated
  --help, -h     Show this help
EOF
}

FORCE=false
FORCED_LANG=""
DRY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=true; shift ;;
    --lang)  FORCED_LANG="$2"; shift 2 ;;
    --dry-run) DRY=true; DRY_RUN=true; shift ;;
    --help|-h) print_usage; exit 0 ;;
    *) log_err "Unknown argument: $1" ;;
  esac
done

# ----- Detect languages -----
DETECTED=()

detect_languages() {
  [[ -f "package.json" ]]                  && DETECTED+=("node")
  [[ -f "pyproject.toml" || -f "setup.py" || -f "requirements.txt" ]] && DETECTED+=("python")
  [[ -f "pom.xml" ]]                       && DETECTED+=("java")
  [[ -f "build.gradle" || -f "build.gradle.kts" ]] && DETECTED+=("java")
  [[ -f "go.mod" ]]                        && DETECTED+=("go")
  [[ -f "Cargo.toml" ]]                    && DETECTED+=("rust")
  compgen -G "*.csproj" >/dev/null && DETECTED+=("dotnet")
  compgen -G "*.sln"    >/dev/null && DETECTED+=("dotnet")
}

if [[ -n "${FORCED_LANG}" ]]; then
  DETECTED=("${FORCED_LANG}")
else
  detect_languages
fi

if [[ ${#DETECTED[@]} -eq 0 ]]; then
  log_info "No specific language detected. Using generic-ide + os templates."
  DETECTED=("generic-ide" "os")
else
  # Always include IDE + OS
  DETECTED+=("generic-ide" "os")
fi

log_info "Detected/forced: ${DETECTED[*]}"

# ----- Build content -----
NEW_CONTENT=""
for lang in "${DETECTED[@]}"; do
  template_file="${TEMPLATES_GITIGNORE}/${lang}.gitignore"
  if [[ -f "${template_file}" ]]; then
    NEW_CONTENT+="
# ===== ${lang} =====
$(cat "${template_file}")
"
  else
    log_warn "Template not found: ${template_file}"
  fi
done

# Header
HEADER="# Generated by git-skill on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Languages: ${DETECTED[*]}
# This file is auto-generated. Manual edits preserved on subsequent runs (append mode).
"

NEW_CONTENT="${HEADER}${NEW_CONTENT}"

# ----- Write or merge -----
GITIGNORE_PATH=".gitignore"
if [[ -f "${GITIGNORE_PATH}" ]] && [[ "${FORCE}" != "true" ]]; then
  log_info ".gitignore already exists. Appending."
  if [[ "${DRY}" == "true" ]]; then
    log_info "[dry-run] Would append to .gitignore"
    echo "${NEW_CONTENT}"
    exit 0
  fi
  printf '\n%s\n' "${NEW_CONTENT}" >> "${GITIGNORE_PATH}"
  log_ok "Appended to .gitignore"
else
  if [[ "${DRY}" == "true" ]]; then
    log_info "[dry-run] Would create .gitignore"
    echo "${NEW_CONTENT}"
    exit 0
  fi
  printf '%s\n' "${NEW_CONTENT}" > "${GITIGNORE_PATH}"
  log_ok "Created .gitignore"
fi

exit 0